# Generated by Django 3.1.7 on 2021-06-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPeludo', '0002_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.IntegerField(max_length=20)),
                ('correo', models.TextField(max_length=100)),
                ('direccion', models.TextField(max_length=100)),
            ],
        ),
    ]
